### ISSUE TITLE
composer require command fails

### ISSUE THREAD

**Issue by gdonald** [open-admin-org/open-admin#100]
composer require open-admin-org/open-admin

Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update open-admin-org/open-admin
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - open-admin-org/open-admin[v1.0, ..., v1.0.27] require symfony/dom-crawler ~3.1|~4.0|~5.0 -> found symfony/dom-crawler[v3.1.0, ..., v3.4.47, v4.0.0, ..., v4.4.45, v5.0.0, ..., v5.4.25] but it conflicts with your root composer.json require (^6.3).
    - Root composer.json requires open-admin-org/open-admin * -> satisfiable by open-admin-org/open-admin[v1.0, ..., v1.0.27].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require open-admin-org/open-admin:*" to figure out if any version is installable, or "composer require open-admin-org/open-admin:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by SachinBahukhandi** [comment]
What is the php version, Laravel version you're using?

**Comment by gdonald** [comment]
> php artisan --version
Laravel Framework 10.23.1

> php --version
PHP 8.2.10 (cli) (built: Aug 31 2023 18:52:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10, Copyright (c), by Zend Technologies

**Comment by SachinBahukhandi** [comment]
I suppose you're using an old version of : `symfony/dom-crawler`. Can you post `composer.json` as well?

**Comment by gdonald** [comment]
> grep 'symfony/dom-crawler' composer.json
        "symfony/dom-crawler": "^6.3"

This is a brand new Laravel project.

**Comment by SachinBahukhandi** [comment]
It seems you're using dom-crawler in your project which conflicts with the package's version. I cannot see dom-crawler coming up with the default `composer.json`.https://github.com/laravel/framework/blob/2bfb70bca53e24227a6f921f39d84ba452efd8e0/composer.json

**Comment by open-admin-org** [comment]
@gdonald we'll soon support dom-crawler 6 already tested locally. Use 5 for the time-being if possible
