### ISSUE TITLE
Not able to copy and modify login page

### ISSUE THREAD

**Issue by bhar-prnv** [open-admin-org/open-admin#101]
There is no option to publish views.
I want to change html for admin login page . Please suggest how can I do that without affect core files.

**Comment by open-admin-org** [comment]
@bhar-prnv 

1) In app/admin/bootstrap.php
`app('view')->prependNamespace('admin',` resource_path('views/admin/'));`

2) add your login template file here
resources/views/admin/login.blade.php

**Comment by iinjaz-token** [comment]
HI , in the Admin/Scaffold I'm getting : Error
Method Illuminate\Database\MySqlConnection::isDoctrineAvailable does not exist.


please help

**Comment by itslucifero** [comment]
Sadly Doctrine is no longer supported in Laravel 11.X so just downgrade to Laravel 10 and use it !!

**Comment by itslucifero** [comment]
> HI , in the Admin/Scaffold I'm getting : Error Method Illuminate\Database\MySqlConnection::isDoctrineAvailable does not exist.
> 
> please help

Sadly Doctrine is no longer supported in Laravel 11.X so just downgrade to Laravel 10 and use it !!

**Comment by azraf** [comment]
> HI , in the Admin/Scaffold I'm getting : Error Method Illuminate\Database\MySqlConnection::isDoctrineAvailable does not exist.
> 
> please help

To use OpenAdmin in Laravel 11, you have to replace one file of that package: src/Console/ResourceGenerator.php You can find it from OpenAdmin official github repo, but not in Main Branch, but check the Develop branch.

Just replace the https://github.com/open-admin-org/open-admin/blob/develop/src/Console/ResourceGenerator.php file with your OpenAdmin main openadmin package file, then the resource generator will work smoothly.

**Comment by tefhabaa** [comment]
Error
Method Illuminate\Database\MySqlConnection::isDoctrineAvailable does not exist.
