### ISSUE TITLE
How to use DomPDF with Open Admin?

### ISSUE THREAD

**Issue by lordjack** [open-admin-org/open-admin#104]
Hey guys,

Someone here would have some example of how to use [DomPDF Laravel](https://github.com/barryvdh/laravel-dompdf) with Open Admin. And also how to add a button to issue a report indicating this arrow?

![image](https://github.com/open-admin-org/open-admin/assets/6691621/e82b74c0-bc4b-413d-9741-651bf27f6079)

Thank you very much in advance.

**Comment by RCyrix** [comment]
Hi there, regarding PDF you will need to define a route outside of the open-admin middleware and check against auth via the Admin facade (Will allow you to check if user is logged in etc) 

I Do not use DOMPDF i use MPDF 

But either way you will need to create the request outside of open admin middleware as open-admin wraps the response in other content (menu etc) 

So define a route outside of admin middleware, to check if user is authed / logged in use Admin facade and continue like a normal laravel pdf, 

Use grid tools to add the button, documentation can be found on the docs site 

If you are looking to build a custom export, you will need to pass open admin grid an exporter and install the laravel:excel package, you will find more information in the documentation 

I am currently building pdfs without issue when following above steps

**Comment by RCyrix** [comment]
When creating the pdf from Open Admin, do a hard re-direct  to the pdf route 

Open admin is a single page app and a soft redirect will simply request content and shove it in to the pjax container, 

so its important to do a full redirect, use a JS redirect

**Comment by lordjack** [comment]
> When creating the pdf from Open Admin, do a hard re-direct to the pdf route
> 
> Open admin is a single page app and a soft redirect will simply request content and shove it in to the pjax container,
> 
> so its important to do a full redirect, use a JS redirect

Would you have any examples @RCyrix?

I wanted to customize the blade of this page to add this button. Passing the PDF route.

**Comment by RCyrix** [comment]
Just build out a standard MPDF controller with a standard route outside of open-admin middleware and treat it like a normal laravel development, once you are out of open-admin middleware its just like building a normal pdf... you are only passing the data from open admin.

**Comment by RCyrix** [comment]
or DOM PDF it doesnt matter, just pass the data to the route

As for adding the button to the grid please check the documentation
