### ISSUE TITLE
How to translate fields in Open Admin

### ISSUE THREAD

**Issue by lordjack** [open-admin-org/open-admin#105]
Hello guys, 

Does anyone know how to do to translate the fields on Open Admin?
![image](https://github.com/open-admin-org/open-admin/assets/6691621/3e47e8d5-d50c-4c4b-ae64-2b4080989968)

I tried to translate going in this file as image 2 shows, but it didn't work.
![image](https://github.com/open-admin-org/open-admin/assets/6691621/77d3a7d0-c415-45b7-9603-88b73adff451)

Thank you very much in advance.

**Comment by RCyrix** [comment]
currently functionality to  add language translations from the front end is not supported. Add it in the file.

**Comment by RCyrix** [comment]
If you are looking to do translations, I built myself a dynamic translator using the JSON component and a function 

I allow the user to choose his language for application 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/f82516d4-56cb-4dea-ba0f-18a390823d4f)

This is stored as a json column in the database and processed to display the users selected lang 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/75c6fc1f-db6a-4d38-9e18-d6650eb9a009)

![image](https://github.com/open-admin-org/open-admin/assets/124294361/5d4cf2fe-dc4e-4998-917b-87bb8768b66b)

**Comment by RCyrix** [comment]
In the JSON array i store the locale and value 

{{locale:ZL, value:YourValue}}

I iterate over each checking if theres a value to display else fall back to primary label

**Comment by lordjack** [comment]
> In the JSON array i store the locale and value
> 
> {{locale:ZL, value:YourValue}}
> 
> I iterate over each checking if theres a value to display else fall back to primary label

Thanks for your response @RCyrix. Would you have the example of some code of how you did this?

**Comment by RCyrix** [comment]
Perhaps the way i went about it is not suitable for all

I have added a column to admin_users and updated the user profile controller to allow selection of locale which i can then access via the Admin::class facade 

public static function translate($translationArray){
        $userLocale = Admin::user()->locale ?? 'en';
        foreach($translationArray as $arrKey => $translationArr){
            if($translationArr){
                $translations = $translationArr['translations'];
                foreach($translations as $translation){
                    if($translation['locale'] === $userLocale){
                        $translationArray[$arrKey]['text'] = $translation['value'];
                    }
                }
            }
            unset($translationArray[$arrKey]['translations']);
        }
        return collect($translationArray)->pluck('text','value')->toArray();
    }

**Comment by RCyrix** [comment]
wow that came out really bad  github....

**Comment by RCyrix** [comment]
gonna see if i can tidy that up

**Comment by RCyrix** [comment]
i dunno, its not formatting the code 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/894a660c-0546-4875-9ac8-c78387122110)

**Comment by RCyrix** [comment]
you can modify the output as needed

**Comment by RCyrix** [comment]
So play around with the json controll a bit, see how it stores the values in json format, once the model cast is on, its like working with a normal array that you can just check

**Comment by RCyrix** [comment]
$translationArray is the column that stores the json array 

So if you have a table called assets 

it would be assets.translations
(I would suggest storing as text)

**Comment by RCyrix** [comment]
[{"locale":"afr","value":"Franchise"}]

 an example of an existing entry

**Comment by RCyrix** [comment]
please note the dynamic translator only works for grid, form and show component controls, you will for standard UI need lang files, things like buttons, titles etc, some you will be able to override others will require file entry

**Comment by open-admin-org** [comment]
@lordjack 
The language for the backend is defined by: config/app.locale

Please refer to https://laravel.com/docs/10.x/localization#defining-translation-strings to see how the translation files are structured in relation to the variables.
In your case the template variable doesn't work because of the . in the your variable name. 

Rename your variable to admin_create. Then in your blade template file you can use:
`{{ __('admin.admin_create') }}`

The part before . relates to the template file. So maybe even create a custom file with you own specific translations. That way in future releases with new languages changes your code won't break if new translation are added to the file.
