### ISSUE TITLE
I want to perform something on Switch change in grid

### ISSUE THREAD

**Issue by akshayrathodar** [open-admin-org/open-admin#125]
how can I perform something on switch change from grid as well as from edit form. I want to notify users by mailing them but I don't know how can i get call back.

**Comment by RCyrix** [comment]
Hi there, 

(I did not read properly, please see message regarding row action, i think would be best way to go)  a $grid->column()->view('your-view') which contains a button with a function behind it, when you click the button, it fires of a js ajax or xhttp request against admin platform (remember to pass your token if post request etc) 

The endpoint can fire off your logic, send mail and log etc 

Return a status to the grid which can just be updated 

A switch "switches" a value. a boolean, for example, enabled | disabled, true|false, not really complex logic (If you use switch on grid, ensure it has correlating switch on form)

To achieve what you are looking to do will require a custom view, check on the open admin docs under the "Grid" section, it will contain the view() and instructions on how to use it, from there you on standard html and js and can do what you need and handle the response

**Comment by RCyrix** [comment]
I mean i suppose you could use a form hook, like saving, check for the value etc, but i can see issues with that :? You could also extend the switch form component and override, but i cant say to much about that as i have only done very basic component overrides etc

**Comment by RCyrix** [comment]
But in the end, would it not be best to use a row action? This will allow you to pass the value from the grid to a class which contains your logic and allows a refresh / return of notification 

So theres a few options i think

**Comment by RCyrix** [comment]
https://open-admin.org/docs/en/model-grid-actions

Row actions will allow you to execute a change on the data and refresh to update that data, for example, show the value as a bool() on the grid, at first will show an "X" , row actions carries out what you want done, refreshs and shows a green tick for the given row 

Batch action may suite you as well

**Comment by akshayrathodar** [comment]
Got Solution 

protected function form() 

can handle it. 

I've just added this 

`        // callback after save
        $form->saved(function (Form $form) {
            //...
            $changes = $form->model->getChanges();
            if (isset($changes['status']) && $changes['status'] != 0) {
                $client_email = $form->model->getAttribute('email');
                $client_name = $form->model->getAttribute('name');
                $property_name = $form->model()->getAttribute('property_name');

                $data = array('name' => $client_name, 'p_name' => $property_name);
                Mail::send('mailapproved', $data, function ($message) use ($client_name, $client_email) {
                    $message->to($client_email, $client_name)->subject('Approved');
                    $message->from('demo@gmail.com', 'Demo');
                });
            }
        });`
 
N All Set 💯

**Comment by RCyrix** [comment]
interesting :? thank you for the feedback!  keep well
