### ISSUE TITLE
UserController override

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#133]
Hi, I need to add an additional field to the admin_users table. I succeeded, but I don't know how to override UserController to make this field appear inside the form. Can you tell me how I can do it? Thank you

**Comment by RCyrix** [comment]
Hi there 

My suggestion would be to copy the controller, change namespace and create a resource route that points at the new controller, can remove any fluff like extra functions etc, config allows you to change user model (Substitute for your own [config/admin.php])

![image](https://github.com/open-admin-org/open-admin/assets/124294361/e2bc3636-b2a7-457a-825d-fa0f3ce3fddd)

Controller you will need to build yourself, if you want to override the built in routes, can use middleware to hook onto request route, identify if internal /admin/auth route and override and redirect to your own controller 

Perhaps some one else can chip in with a better solution, 

@open-admin-org  maybe to look at allowing a user controller override  if its a frequent thing

**Comment by gfsoluzioni** [comment]
Hi, thanks for the immediate response, but I'm not clear on the last part. Can you give me some examples please? It is very important for me to solve this problem. Thank you

**Comment by RCyrix** [comment]
so open admin comes with a set of routes 

/admin/auth/

users, 
own profile
etc 

So if you want to override those you would need to use middleware to hook on to request and identify the request endpoint, then just override and redirect to your own 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/27b86a30-fb31-4647-bc3c-5b84771d9b6c)

https://laravel.com/docs/10.x/middleware#main-content

**Comment by RCyrix** [comment]
Please note the above is a simple middleware example, just to show how middleware looks in code, more info can be found on the docs

**Comment by gfsoluzioni** [comment]
Hi, I found a solution that partly works, that is, I copied, as you told me, the UserController inside app/controlles, renaming it to CustomuserControlle and changing the namespace. In this way I am able to display the new field within the form, but I am unable to set the relationships within the model, as it takes the form one by default. How do I override the Users model???

**Comment by RCyrix** [comment]
> Hi there
> 
> My suggestion would be to copy the controller, change namespace and create a resource route that points at the new controller, can remove any fluff like extra functions etc, config allows you to change user model (Substitute for your own [config/admin.php])
> 
> ![image](https://private-user-images.githubusercontent.com/124294361/294912204-e2bc3636-b2a7-457a-825d-fa0f3ce3fddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjIzNDQsIm5iZiI6MTcwNDcyMjA0NCwicGF0aCI6Ii8xMjQyOTQzNjEvMjk0OTEyMjA0LWUyYmMzNjM2LWIyYTctNDU3YS04MjVkLWZhMGYzY2UzZmRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxMzU0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQwZjE3ZWMxNWIwZDk5Njk5NjdkNzVhMjI3NTNjOWFiY2ViNTFlZTI1ZWNlZjAzYTUwNGE1YzllNzJhZmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cj6vFt0kxjTdxv7iIt7LnbonHwGfqp9_w6QZve_zzfA)
> 
> Controller you will need to build yourself, if you want to override the built in routes, can use middleware to hook onto request route, identify if internal /admin/auth route and override and redirect to your own controller
> 
> Perhaps some one else can chip in with a better solution,
> 
> @open-admin-org maybe to look at allowing a user controller override if its a frequent thing

Please read this message again, it shows you in the config where you can override user model

**Comment by gfsoluzioni** [comment]
And is it possible to override the Users model?

**Comment by RCyrix** [comment]
Yes Please read my previous messages, i clearly state that user model can be overridden and i provide you a snap shot of config with config key users_model with the namespace and name of your desired model....

**Comment by migcosta** [comment]
> I succeeded, but I don't know how to override UserController to make this field appear inside the form.

@gfsoluzioni you can use the hooks for that: https://open-admin.org/docs/en/admin-controller-hooks#the-hooks

1. create a new controller that extends the UserController Class:

```
namespace App\Admin\Controllers;
use OpenAdmin\Admin\Controllers\UserController;
class ExtendedUsersController extends UserController
{
    public function __construct()
    {
        $this->hook("alterForm", function ($scope, $form) {
            // add the field here
            $form->text('testField');
            return $form;
        });
    }
}
```

2. Override the the auth/users route and point it to your new controller:
app\Admin\routes.php

```
function (Router $router)
{
   ...
   $router->resource('auth/users',  App\Admin\Controllers\ExtendedUsersController::class)->names('admin.auth.users');
 }
```

And that will allow you to "override" the UserController.
@open-admin-org maybe it would be useful a section on overrides in the docs.

**Comment by RCyrix** [comment]
interesting! Thanks for that @migcosta 

Id seen the hooks in the field,show,and form  but was not sure of how they were utilized, im not sure if this is new or something i completely missed 

https://open-admin.org/docs/en/admin-controller-hooks

It seems theres a section already
