### ISSUE TITLE
Save file as base64 in to blob column

### ISSUE THREAD

**Issue by philips81** [open-admin-org/open-admin#134]
Hi,
I don't understand how you can save a file as base64 in a blob field.
I inserted in the Model file:

`class FileModel extends Model
{
    protected $fillable = [
        'file_data'
    ];
}`

How can I save base64 in database? Should I use Model form callbacks?
If I use the public function store(Request $request) method it gives me an error.

Thanks

**Comment by RCyrix** [comment]
Hi there, you can define a saving hook, process the file content into a base64 encoded string that you store as a text, do with the file what you will after the save

**Comment by RCyrix** [comment]
Perhaps i stand under correction but being a resource the route utilizes the store functions on higher levels of the inheritance chain, the model form call back will give you access to the value and allow you to process it, if you want to upload for example via ajax, you will need to define a route and point it to a controller with the function that handles the request, you wont be able to use store

**Comment by philips81** [comment]
Hi,
thanks for your help.
I solved it by creating a route in api.php which is called in the action of the form. 
I intercept the form request, create the base64 and save in the database with the eloquent create or update methods.

**Comment by RCyrix** [comment]
great to hear

**Comment by RCyrix** [comment]
Hi there, may i ask that you close the ticket from your side? 

Kind regards
