### ISSUE TITLE
Graphics issues with Quick Create

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#137]
Hi, as you can see from the screenshot the display of the two selects is not perfectly aligned and pleasant. How can I solve this graphics problem??

![quick_create_problem](https://github.com/open-admin-org/open-admin/assets/121958/e70c85bf-c95e-45f5-b401-8d17b0c87abb)

**Comment by RCyrix** [comment]
Hi there, I have not come across this issue, (I have used the quick create quite a bit) so i can only offer ideas to check.

Being that it works in my use cases, i would suggest checking the javascript console,
 i usually find select components etc fail when there is a javascript error, for example repeating a column name, or a failure in a script  you have in a view etc if you have any included views etc, so all i can suggest with the little bit of info you have provided is to double check for console errors, try one component at a time and systematically identify where it fails and present that information, please include a snippet of the code that you have used to intiialize the component and steps you've taken to test it then we can be on the same page and be better able to assist
