### ISSUE TITLE
How to pass values ​​into an action class from a grid

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#138]
Hi, I would need the values ​​inside a form present in an action class that I call via a button present in the header of the grid generated in the form of a relation. Can you help me?? Thank you

**Comment by RCyrix** [comment]
Hi there, could you give a bit more info on what you are looking to achieve? 

You could use a row action or a batch action to take action on row entries in the grid,

Batch action can show either a button on the grid that appears when you select entries, or shows as a option in the drop down menu (Batch edit, Batch delete, Your Option etc) 

Please see the below docs link

https://open-admin.org/docs/en/model-grid-actions
https://open-admin.org/docs/en/model-grid-custom-tools 

Row action would allow for selection of entry in grid, it passes the model to an "action  class" 

Batch action allows you to select all or cherry pick which entries in the grid you would like to pass and allows you to process each one

**Comment by gfsoluzioni** [comment]
![fiche](https://github.com/open-admin-org/open-admin/assets/121958/5303c19c-1814-44ba-8063-7858395c70e5)

Hi I actually wanted to create a custom create action on a grid created as a hasmany relation of a model. I actually wanted to create a custom creation action by passing the id of the model from which I create the relationship and the grid inside the detail view.

**Comment by gfsoluzioni** [comment]
Ciao, potresti darmi una risposta al quesito sopra indicato?
