### ISSUE TITLE
RowAction not working

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#141]
Hi, I have implemented a RowAction as per documentation to edit a template. When I click the Save button, I get the following error: OpenAdmin\Admin\Form::model(): Return value must be of type Illuminate\Database\Eloquent\Model, OpenAdmin\Admin\Actions\Interactor\Form

This is my snipper:

`<?php

namespace App\Admin\Actions;

use Illuminate\Database\Eloquent\Model;
use OpenAdmin\Admin\Actions\RowAction;
use Illuminate\Http\Request;
use App\Models\Clienti;

class ModificaFiche extends RowAction
{
    public $name = 'Modifica fiche';

    public $icon = 'icon-edit';

    public function handle(Model $model, Request $request)
    {
        // $model ...
        $model->id_cliente = $request->get('id_cliente');
        $model->save();
        return $this->response()->success('Salvataggio effettuato con successo...'.$model->id)->refresh();
    }
    
    public function form()
    {
        $this->select('id_cliente', 'Cliente')->options(Clienti::all()->pluck('nominativo','id'));
    }
}`

Can I help you?

**Comment by emmanpbarrameda** [comment]
check this out: https://github.com/open-admin-org/open-admin/issues/72?fbclid=IwAR1TlqUaKeSQSzw-dQad74uua8R4txylzydtrFtJjBzLpO9P_64NdO3Xj2s
