### ISSUE TITLE
Batch Actions

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#145]
Hi, I have implemented, as per the documentation, a batch action directly on a grid, but I get this error: 
[recording (2).webm](https://github.com/open-admin-org/open-admin/assets/121958/c6a779d3-3d26-44b7-8597-07504de43447)

How can I solve it?

**Comment by seaatif** [comment]
You need to check the type of Arguments that **handle** function is expecting in **Sconto** class. It must be the type of collection. 

You might have generated the action with wrong type if you generated it through command line. There is a separate argument in command for batch action. 

`php artisan admin:action **NameOfTheAction** --grid-batch `
