### ISSUE TITLE
Cascading select

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#148]
Hi, I followed the procedure to implement a Cascading select to the letter, but I always get the same error: Uncaught ReferenceError: choices_servizi is not defined

I attach code:

![image](https://github.com/open-admin-org/open-admin/assets/121958/18a005cd-f528-4941-92fa-60d5444bdaeb)

The json I get via the call complies with your documentation:

![image](https://github.com/open-admin-org/open-admin/assets/121958/d6a1d9b0-4162-4e3c-bae2-5af8c96b413b)

How can I solve this problem?

**Comment by RCyrix** [comment]
please drop a snapshot of the route and function on the endpoint and a snapshot of the javascript console when selecting an option.. thanks

**Comment by gfsoluzioni** [comment]
> please drop a snapshot of the route and function on the endpoint and a snapshot of the javascript console when selecting an option.. thanks

Hi, thank you for the reply and I apologize for the previous post, but I'm not afraid of a diet that alone won't cause me problems. I invite you to your richest screenshot:

![image](https://github.com/open-admin-org/open-admin/assets/121958/e4acabc0-e7e8-45ca-a15a-22a7b7b6e329)

![image](https://github.com/open-admin-org/open-admin/assets/121958/3fbe8bb4-326f-4b26-b7e5-1c26adc15e90)

![image](https://github.com/open-admin-org/open-admin/assets/121958/6e1b14bf-d80d-45cb-8dc7-7732aee0bd7a)

I look forward to hearing from you and thanks again for the help

**Comment by RCyrix** [comment]
Please try something along these lines

This is how i satisfy the select components requirements

![image](https://github.com/open-admin-org/open-admin/assets/124294361/fa159411-da6d-4130-9f15-0ae155250666)

Gather the result with eloquent and just build out an array containing the expected values 


And secondly use a post route, you will be able to clearly see the type of request actuated by the interface on the change event... open the network monitor and view the request. You will see a response. This end point is not supported.... 

Please use a post endpoint. The select component handles tokenization

**Comment by gfsoluzioni** [comment]
> monitor di rete

Hi, I created the method you indicated inside my controller (ServiziController):

![image](https://github.com/open-admin-org/open-admin/assets/121958/5909176b-c709-4b1c-8748-2e46733cadbc)

Then I created a post route like this:

![image](https://github.com/open-admin-org/open-admin/assets/121958/a7b05432-6c78-4aff-b2bd-9e4ae1718a81)

Then inside the form I modified it like this:

![image](https://github.com/open-admin-org/open-admin/assets/121958/10cf30e2-3ccf-4310-bc32-00eeb47b68ba)

when I use the Chrome inspector and go to the network, when I select the category nothing appears. Where am I wrong?

![image](https://github.com/open-admin-org/open-admin/assets/121958/56cd31df-45a5-428b-9713-ee5c46e803b8)

**Comment by RCyrix** [comment]
Seems I can't help further here, I have used the component a multitude of times across multiple projects, 

Please step over the process you followed to implement the select, it does work, I am unable to see the direct cause of the issue, something small most likely, else you will need to be patient for another community member who can perhaps see what the problem is

**Comment by gfsoluzioni** [comment]
> Sembra che non posso aiutarti ulteriormente qui, ho utilizzato il componente una moltitudine di volte in più progetti,
> 
> Per favore, ripercorri il processo che hai seguito per implementare la selezione, funziona, non riesco a vedere la causa diretta del problema, qualcosa di piccolo molto probabilmente, altrimenti dovrai essere paziente per un altro membro della comunità che forse può vedere cosa sta succedendo il problema è

All this is very strange also because I followed the documentation to the letter and as you can see from the screenshots of the first ticket the api method correctly processes the json for populating the second select. Is it possible that this doesn't work because I used the form method inside an Action class, therefore when opening a modal popup? Also can I ask you and then I won't bother you anymore for a complete example? Maybe I'm wrong. I thank you in advance

**Comment by RCyrix** [comment]
it could be, I am not sure how the author handles it, but i know the popup form does ask to please keep it simple for now, i think the best thing is to actually try it in a normal form and see if it works, i am not sure a popup form is able to handle the load etc, 

best way is to try it and see, 

You are not bothering me, if i am able to assist when i can i will, if im not able to assist or do not have an awnser for you  then i cant help, nothing funny about it

**Comment by RCyrix** [comment]
I'm not able to find the documentation snippet now but yeah try to keep it simple on the popup form i dont think it has all the functionality, but best is to try and see with a controller form

**Comment by gfsoluzioni** [comment]
> I'm not able to find the documentation snippet now but yeah try to keep it simple on the popup form i dont think it has all the functionality, but best is to try and see with a controller form

Yes, I confirm that it works from the controller. Too bad it doesn't work inside an Action class called via modal popup. Thanks again for your support and time

**Comment by phar-dev** [comment]
could you solve it? i have same isue, json response correctly but 2nd select does not fill

**Comment by handrinata** [comment]
I've done it in my own project, probably some Miss in the one of the following,
1. Id in parent select, (maybe doesnt match)
2. Create router that catch the post url, (maybe go somewhere else)
3. Create function so it'll catch $query parameter, to get other array for the 2nd select (maybe missed it)
4. Return the 2nd array with exact format as the example. Last time i finalize my return format with return response()->Json($myreturn); 
5. Repeat if multi cascade.
