### ISSUE TITLE
Hide/show components based on user role

### ISSUE THREAD

**Issue by AndreasMySch** [open-admin-org/open-admin#149]
Hi there, I can restrict views depending on user role, but I want to know if menu_items can be hidden / shown based on current users role as well?

**Comment by RCyrix** [comment]
Hi there 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/edc2900c-e465-4fad-a508-d19d741071d5)


Please see the config file and try these flags

config/admin.php

**Comment by RCyrix** [comment]
Also please see 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/a877bef7-4c60-4f19-961b-b93713791ead)
