### ISSUE TITLE
Documentation is not correct on grid column date format.

### ISSUE THREAD

**Issue by bytebrain** [open-admin-org/open-admin#15]
Hi,

I found a issue with the documentation of the date format of a grid column. https://open-admin.org/docs/en/model-grid-column-display#date-format 

It says the following to use;
```php
$grid->column('created_at')->DatetimeFormat('Y-m-d');
```

But that results in an exception:
```
BadMethodCallException In Macroable.php line 87 :
[  Method Illuminate\Support\Str::DatetimeFormat does not exist.]()
```

However when I check the source, there is a method `dateFormat` and it works.
```php
$grid->column('created_at')->dateFormat('Y-m-d');
```
So I think the documentation is not correct?
Great work on this fork! Thanks!

**Comment by open-admin-org** [comment]
Your right, thanks for the notice. I updated the documentation.
