### ISSUE TITLE
Grid mode have nested same mode Tree?

### ISSUE THREAD

**Issue by hoangnamitc** [open-admin-org/open-admin#19]
Hello,

I used z-song laravel-admin and i'm know this package and i have question this package have nested category in Grid mode same is Tree?

Thanks!

**Comment by open-admin-org** [comment]
Hi @hoangnamitc,

Not sure if i fully understand you question.
Are you revering to: https://open-admin.org/docs/en/model-tree ?
This functionality is a little experimental, and might needs further development to fit your needs.

**Comment by hoangnamitc** [comment]
Hi @open-admin-org ,

My mean is how to use **Model-grid** can view like below (Nested parent and children)

<img width="678" alt="image" src="https://user-images.githubusercontent.com/7042462/171188544-8be68e75-4f7b-4407-a5b6-05f0dbd2c4d1.png">

**Comment by open-admin-org** [comment]
Model grid can not be used like this. Laravel-admin also uses model-tree in this case. The implementation with https://open-admin.org/docs/en/model-tree is not fully developed to work out of the box, so if you like to use this you need to write some more code around it.

Hopefully we can work on a better implementation in the future. If you had any success with writing some nice code please let us know. Maybe we can implement this.

**Comment by open-admin-org** [comment]
I think this is what you are looking for, this replaces the default index (grid view) with a view that is in Tree view mode. 
Please refer to: https://open-admin.org/docs/en/model-tree for the database schema.
Good luck with it.

file: App/Models/Category.php
```
<?php

namespace App\Models;

use OpenAdmin\Admin\Traits\AdminBuilder;
use OpenAdmin\Admin\Traits\ModelTree;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use ModelTree;
    use AdminBuilder;

    protected $table = 'categories';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setParentColumn('parent_id');
        $this->setOrderColumn('order');
        $this->setTitleColumn('title');
    }
}

```

file: App/Admin/CategoryController.php
```
<?php

namespace App\Admin\Controllers;

use OpenAdmin\Admin\Controllers\AdminController;
use OpenAdmin\Admin\Form;
use OpenAdmin\Admin\Grid;
use OpenAdmin\Admin\Show;
use OpenAdmin\Admin\Layout\Content;
use App\Models\Category;

class CategoryController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'Category';

    public function index(Content $content)
    {
        return $content
            ->title($this->title())
            ->description($this->description['index'] ?? trans('admin.list'))
            ->body(Category::tree());
    }

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new Category());

        $grid->column('id', __('Id'));
        $grid->column('parent_id', __('Parent id'));
        $grid->column('order', __('Order'));
        $grid->column('title', __('Title'));

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(Category::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('parent_id', __('Parent id'));
        $show->field('order', __('Order'));
        $show->field('title', __('Title'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new Category());

        $form->number('parent_id', __('Parent id'));
        $form->number('order', __('Order'));
        $form->text('title', __('Title'));

        return $form;
    }
}

```

**Comment by hoangnamitc** [comment]
Thanks Bro !

I'm will try your code.
I hope this package will develop more in the future
