### ISSUE TITLE
multipleSelect does not work in Popup form - actions

### ISSUE THREAD

**Issue by Tech-Loyal** [open-admin-org/open-admin#190]
**Describe the bug**
When creating a list of multiple selections in the Popup form, RowActions shows an error (with 'select' it works).

**To Reproduce**
Code of the actions
`class SendWorkDetails extends RowAction
{
    public $name = 'Send Work Details';

    public $icon = 'icon-file-download';

    public function form()
    {
       $emails = SendEmail::where('status', 1)
            ->pluck('name', 'id')
            ->toArray();

        $this->multipleSelect('emails', 'Send emails')
            ->options($emails);
    }

    public function handle(Model $model, Request $request)
    {
        $emailIds = (array) $request->get('emails');
        $emails = SendEmail::whereIn('id', $emailIds)
            ->pluck('email')
            ->toArray();

           $workDetails = [
            'alias' => $model->alias,
            'description' => $model->description,
            'date_start' => $model->date_start,
            'date_end' => $model->date_end,
            'responsible' => $model->responsible,
            'sede' => $model->sede->name,
            'area' => $model->area->name,
            'budget' => $model->budget,
            'observation' => $model->observation,
        ];

          foreach ($emails as $email) {
            Mail::to($email)->send(new WorkDetailsMail($workDetails));
        }
        
        return $this->response()->success('Exito!')->refresh();
    }
 }`
 
![Screenshot_21](https://github.com/user-attachments/assets/8ce4b003-c16d-41b9-a221-d38e9070d29f)

**Expected behavior**
I need a multipleSelect to be displayed in the Popup form to select several emails
**System**
 - Open-admin version = v1.0.27
 - PHP version = 8.1
 - Laravel Version = 10.10
 - OS: Windows
 - Browser chrome

**Comment by Ladel** [comment]
Сheck it out

```php
public function form()
{
   $emails = SendEmail::where('status', 1)
        ->pluck('name', 'id')
        ->toArray();

    $this->addValues(); // add this

    $this->multipleSelect('emails', 'Send emails')
        ->options($emails);
}
```

**Comment by Tech-Loyal** [comment]
It's amazing how a line of code can solve so many things, thank you very much for the prompt response.
