### ISSUE TITLE
add relationship to built-in open-admin authentication user

### ISSUE THREAD

**Issue by brilyanhidayat** [open-admin-org/open-admin#28]
is possible to add relationship (profile or employee table) to built-in open-admin authentication user?

**Comment by open-admin-org** [comment]
Not sure if I understand correctly. 

To be clear, the admin users for open-admin are separated from the default Laravel user table.

- Maybe you are looking for the rights system?
In that case you could add different roles for each type of admin user. See the user section in the admin panel and check" https://open-admin.org/docs/en/permission for more info.

- If you are looking to add an relationship to the admin users you can create you own model and alter this in the config/admin.php. Then you could copy OpenAdmin/Admin/Controllers/UserController.php to your app/Admin/Controllers folder and alter the controller to your own needs.

Good luck and happy coding.

**Comment by open-admin-org** [comment]
No-fix needed
