### ISSUE TITLE
flatpickr: invalid locale zh-CN

### ISSUE THREAD

**Issue by fenghuang889900** [open-admin-org/open-admin#29]
**Describe the bug**
flatpickr: invalid locale zh-CN

**To Reproduce**
1.app.php set lang to zh-CN
2.include zh.min.js
3.reload page 
4.report flatpickr: invalid locale zh-CN

**Expected behavior**

**System**
 - Open-admin: laster 
 - PHP: 8.0
 - Laravel 9
 - OS: MAC
 - Browser chrome

**Comment by fenghuang889900** [comment]
`$grid->filter(function (Grid\Filter $filter){
            $filter->disableIdFilter();
            $filter->between('day', '日期')
                ->datetime(['format'=>'YYYY-MM-DD','locale'=>'zh']);
        });`

**Comment by open-admin-org** [comment]
@fenghuang889900 Thanks for reporting this bug. Its is solved in v.1.0.21. 
It now passes along the options arrays in the date / day / month / time / year filters as well.

**Comment by shadirok** [comment]
still getting Error: flatpickr: invalid locale de
