### ISSUE TITLE
Application Skin configuration not working.

### ISSUE THREAD

**Issue by saptakchatterjee** [open-admin-org/open-admin#37]
Application skin configuration as written within config/admin.php :
/*
    |--------------------------------------------------------------------------
    | Application Skin
    |--------------------------------------------------------------------------
    |
    | This value is the skin of admin pages.
    | @see https://adminlte.io/docs/2.4/layout
    |
    | Supported:
    |    "skin-blue", "skin-blue-light", "skin-yellow", "skin-yellow-light",
    |    "skin-green", "skin-green-light", "skin-purple", "skin-purple-light",
    |    "skin-red", "skin-red-light", "skin-black", "skin-black-light".
    |
    */
    'skin' => 'skin-blue-light',

this configuration is not working as I can't see any changes with the color in admin panel pages, while I'm changing the value with a different one as described within comment.

**System**
 - Open-admin version : latest as I tried with a fresh installation
 - PHP version : 8.1
 - Laravel Version 9.41.0
 - OS: Linux
 - Browser: Google Chrome, Firefox

**Comment by NealRyanCruickshank** [comment]
Hi there, I had a look into this, i saw a line commented out but the class is being echo'd out in the view in the body tag, however i find its not changing the navbar and sidebar, so I'm gonna dig a bit deeper and see where I can assist and get everything to change together, also to the ones who started this project THANK YOU!!! I really liked encore/z-song and sad to see it no longer maintained, but this is amazing well played!!

**Comment by open-admin-org** [comment]
@saptakchatterjee Thank for reporting
@NealRyanCruickshank Thank you.

This feature is indeed removed. Maybe in a later stage we'll add more theming options. You could overwrite style with the custom skin class.

Open is based on bootstrap5, ff you are interested in changing these styles you could take a look at
/vendor/open-admin-org/open-admin/resources/assets/open-admin/scss

These are compiled with sass via composer. You can run "composer sass" inside /vendor/open-admin-org/open-admin to create a new version of the css. Be aware you need to push you news styles to public root as well. Y
ou can use: 
`php artisan vendor:publish --provider="OpenAdmin\Admin\AdminServiceProvider"`

To make development more easy i created myself a symbolic link between my asset folder in vendor dir and the vendor/open-admin dir in the public root.

Happy coding!

**Comment by phar-dev** [comment]
I've tried it but I can't get any changes on my theme, mi composer sass compile on vendor, but when I publish I can't see any changes.
