### ISSUE TITLE
2 Form linkage bugs

### ISSUE THREAD

**Issue by x-oscarr** [open-admin-org/open-admin#43]
When I started work with Form linkage I encountered 2 bugs:
***
**1. The issue with displaying dynamic fields**
"Dynamic fields" are not displayed after a page has loaded when the display condition is true. For a linkage to work properly, a user must change the condition field (on which the display of dynamic fields depends) to trigger display events. Reproduced for all conditions except '=' (with this condition works properly).

**To Reproduce:**
1. I have condition IN. And I want to display the "Target url" field when a user selects value 301 or 302 for "Code".
![Screenshot_20230128_023632](https://user-images.githubusercontent.com/50730757/215266730-649aa726-0897-47fc-91dc-082024bf9eab.png)
2. When the page has loaded, the "Destination URL" field is not displayed until a user updates the "Code" field. The default value is set as 301. 
**The issue reproduces for new and edit equally**
Demonstration:

https://user-images.githubusercontent.com/50730757/215266932-889efefa-95e6-4d99-acbb-cd6cca01f8c5.mp4

***
**2. Dynamic field values are not saved**
The same field inside the callback function of the when() method and outside works differently. A user can`t save a value if this is a "dynamic field".
Demonstration:

https://user-images.githubusercontent.com/50730757/215267630-e8bcd3b4-4fe7-4875-8e6a-ea6a121b86a3.mp4

**System**
 - Open-admin version: **1.0.25**
 - PHP version: **8.1.14**
 - Laravel Version: **9.48.0**
 - OS: **Win + WLS2 (Linux)** - local server launched on WSL2
 - Browser: **Chrome**

**Comment by x-oscarr** [comment]
Relates to #42

**Comment by open-admin-org** [comment]
@x-oscarr Thanks for detailed issue report!
Fixed in v1.0.26
