### ISSUE TITLE
Decimal mask not displaying correctly (Input mask.js)

### ISSUE THREAD

**Issue by NealRyanCruickshank** [open-admin-org/open-admin#46]
Hello!

I hope all is well,

The decimal type input is not displaying as one would expect, there is an issue regarding the format of the value, it will then save with the incorrect format muddling up the value each time the update form is called 

So if i do a fresh install and use a decimal I get the following behavior

On Create
![image](https://user-images.githubusercontent.com/112626637/216502631-0a9f4f10-35cb-4121-bebb-1523cd2a82d9.png)
 
On Grid after create 
![image](https://user-images.githubusercontent.com/112626637/216502773-41d6d6b5-59c6-452d-94eb-5a45c48fe258.png)

On update [** Where the issue sits **]
![image](https://user-images.githubusercontent.com/112626637/216502848-f1be1571-8efd-4d7d-bfc8-02b2282775ed.png)

If the user doesn't notice this , it gets saved. and when its saved, it will take the value of 30 000 rather than 300.00

I traced this down to /public/vendor/open-admin/inputmask/inputmask.js

Bad excuse but it was late and I ended up making a change to the min.js and managed to get the issue sorted, but i think this is treating the Symptom rather than the root cause, theres a ternary somewhere in the minified / obfuscated dist code, that returns the element, something going wrong there, if the problem is infact in the JS i will be happy to trace it down again

**Comment by NealRyanCruickshank** [comment]
Please find attached (inputmast.js modified)

Though i don't think it will help much in this case 

[Uploading inputmask.min.js…]()

Let me know what I can do from my side! 

I will continue cracking at it over the weekend

**Comment by open-admin-org** [comment]
@NealRyanCruickshank thanks for reporting this issue and supplying a fix. I ended updating the original library which seems to fix the issue. Next to that please also note the field you use should be a field that can handle decimal values. A string field might also work, but that seems a bit out of place.

**Comment by open-admin-org** [comment]
now fixed in v1.0.27
