### ISSUE TITLE
Form linkage -> callbacks not seeing "linked" form inputs

### ISSUE THREAD

**Issue by NealRyanCruickshank** [open-admin-org/open-admin#47]
Hi there

I have a form like the below 

![image](https://user-images.githubusercontent.com/112626637/216856393-03656ce9-00b1-4ea6-a9bb-4e970c2d10e5.png)

A user can either choose from a select box, or the user can type in a few fields, 

When submitting the form, it doesn't pick up on any of the inputs 

![image](https://user-images.githubusercontent.com/112626637/216856523-5b295447-2972-487f-8106-4f8fdcc17461.png)

The result is the same on submitted and saved

**Comment by NealRyanCruickshank** [comment]
![image](https://user-images.githubusercontent.com/112626637/216857395-be55daf7-b09d-43dd-9572-565d5e365a36.png)

The code snippet handling the form linkage,

I tried changing to select etc as well but same thing

**Comment by NealRyanCruickshank** [comment]
Hi! I unfortunately did not manage to figure it out over the weekend, I did however find that this is only affecting numeric type inputs and text, ckEditor, select, list etc seems to work well! 

![image](https://user-images.githubusercontent.com/112626637/217946181-c5ca2c46-694a-4120-a865-a748c8267303.png)

Thanks!

**Comment by open-admin-org** [comment]
Hi @NealRyanCruickshank thanks for reporting this issue. I think this issues was fixed 1.0.25. But it might that you didn't updated the javascripts after the update.
