### ISSUE TITLE
First tab is always active in Tab Widgets

### ISSUE THREAD

**Issue by hrs-o** [open-admin-org/open-admin#51]
**Describe the bug**

First tab is always active in Tab Widgets.

![image](https://user-images.githubusercontent.com/7277266/224652901-28a39a74-2768-4616-997e-8e86b7f1733a.png)

**To Reproduce**

```php
public function index(Content $content): Content
{
    $tab = new Tab();
    $tab->add('1', 'A', false);
    $tab->add('2', 'B', false);
    $tab->add('3', 'C', true); 
    return $content->row($tab);
}
```
This code appears to be unnecessary.
`$this->data['tabs'][0]['active'] = true;`
https://github.com/open-admin-org/open-admin/blob/v1.0.26/src/Widgets/Tab.php#L120-L130

**Expected behavior**

The first tab should not be active.

**System**
 - Open-admin version 
   - [v1.0.26](https://github.com/open-admin-org/open-admin/releases/tag/v1.0.26)
 - PHP version
   - PHP/8.2.3
 - Laravel Version 
   - 10.1.5
 - OS: 
   - Linux
 - Browser 
   - chrome

**Comment by open-admin-org** [comment]
@hrs-o thanks for reporting
now fixed in v1.0.27
