### ISSUE TITLE
Font Awesome brand icon not showing

### ISSUE THREAD

**Issue by hrs-o** [open-admin-org/open-admin#52]
**Describe the bug**
Font Awesome brand icon not showing
![image](https://user-images.githubusercontent.com/7277266/224927739-6ab684eb-40b6-4540-a153-799786ecd1ae.png)

**To Reproduce**

```html
<span class="icon-pen">OK</span>
<span class="fa icon-pen">OK</span>
<span class="icon-github">NG</span>
<span class="fab icon-github">NG</span>
```

If a class starting with icon- is specified, the font face will be fixed to "Font Awesome 5 Free"
https://github.com/open-admin-org/open-admin/blob/v1.0.26/resources/assets/open-admin/scss/fontawesome.scss#L6-L40

**Expected behavior**

A brands icon is displayed

**System**
 - Open-admin version 
   - [v1.0.26](https://github.com/open-admin-org/open-admin/releases/tag/v1.0.26)
 - PHP version
   - PHP/8.2.3
 - Laravel Version 
   - 10.1.5
 - OS: 
   - Linux
 - Browser 
   - chrome

**Comment by open-admin-org** [comment]
@hrs-o thanks for reporting, now fixed in v1.0.27
you can add `fab & fas` in front of icon-
