### ISSUE TITLE
fixedFooter is displayed for HasOne, BelongsTo, MorphIne relations

### ISSUE THREAD

**Issue by hrs-o** [open-admin-org/open-admin#53]
**Describe the bug**
`fixedFooter` is displayed for HasOne, BelongsTo, MorphIne relations

![image](https://user-images.githubusercontent.com/7277266/224932462-cf2054e6-68c2-4b42-be67-bfb883f6abf8.png)

**To Reproduce**
```php
    protected function detail(int $id): Show
    {
        /** @var User $user */
        $show = new Show(User::findOrFail($id));
        $show->field('id', __('id'));
        $show->relation(
            'UserRelation',
            'Relation one',
            static function (Show $showRelation)  {
                $showRelation->name();
            }
        );
        return $show;
    }
```

Show::addField is called because fixedFooter does not exist in Show class.

`$renderable->fixedFooter(false);` 

https://github.com/open-admin-org/open-admin/blob/v1.0.26/src/Show/Relation.php#L100-L129

**Expected behavior**

fixedFooter not displayed

**System**
 - Open-admin version 
   - [v1.0.26](https://github.com/open-admin-org/open-admin/releases/tag/v1.0.26)
 - PHP version
   - PHP/8.2.3
 - Laravel Version 
   - 10.1.5
 - OS: 
   - Linux
 - Browser 
   - chrome

**Comment by open-admin-org** [comment]
@hrs-o thanks for reporting 
now fixed in v1.0.27
