### ISSUE TITLE
Mixed content issue when loading over HTTPS

### ISSUE THREAD

**Issue by nkorent** [open-admin-org/open-admin#61]
**Describe the bug**
When loading /admin over https I get console warnings for mixed content and thus no JS/CSS is loaded.
I have tried adding a variable to .env ADMIN_HTTPS=true but that didn't help.

<img width="1512" alt="Screenshot 2023-05-08 at 22 25 42" src="https://user-images.githubusercontent.com/32095650/236927421-9512777d-6d0a-4c4b-a955-2795304e1427.png">

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Load website over HTTPS
2. visit /admin
3. open console and check for errors

**Expected behavior**
When visiting /admin (or any other route in login) user should have js and css scripts loaded.

**System**
 - Open-admin version 1.0.27
 - PHP version 8.1
 - Laravel Version 8.54
 - OS: Linux
 - Browser: Opera, Safari, Chrome....

**Comment by open-admin-org** [comment]
@nkorent Thanks for the report this issues.
It's really hard to pinpoint the issue without seeing what is loaded over http and what over https. Try do find the file that is loaded by over https but requests the http file. or the other way around: Loaded over http but has a reference to a https.

Did you maybe minify your admin assets? Try clearing them and generate them again. Or see if there reference to http file in the database somewhere.

**Comment by nkorent** [comment]
hey, thank you very much for your reply.

I have tried now redeploying the whole app and have overridden the default variable in the admin config file.

```    /*
    |--------------------------------------------------------------------------
    | Access via `https`
    |--------------------------------------------------------------------------
    |
    | If your page is going to be accessed via https, set it to `true`.
    |
    */
    'https' => env('ADMIN_HTTPS', true),

```

This has fixed the issue I was having.
I think the issue was not in the admin package, but rather in my server and .env.

I'm digging into it, but I will close this since it was not a bug. Thank you very much for your support.
This package rocks, I will contribute here for sure:).
