### ISSUE TITLE
Theme file available for share 

### ISSUE THREAD

**Issue by RCyrix** [open-admin-org/open-admin#64]
Hi there! 

I hope all is well! 

It's not so much a bug more looking to find out more about sharing and collaborating with you if you are willing on a few drop in themes, it sits on top of the current theme and no sass or recompilation required etc, 

 Thus far I've done a "Mocco", "Grey" and "Blue" 
 
 Please see attached 
 
 
![image](https://github.com/open-admin-org/open-admin/assets/124294361/0b22cb71-3108-4f17-bbb0-eb119e7bcd18)

![image](https://github.com/open-admin-org/open-admin/assets/124294361/ad5b6edd-da35-4a70-bd58-b2dda2a56f5b)
![image](https://github.com/open-admin-org/open-admin/assets/124294361/e4507e6c-3fdf-4ff0-8139-bede47184c9f)
![image](https://github.com/open-admin-org/open-admin/assets/124294361/2d24ba7d-99e7-4195-84eb-b458a298a545)

Its still a bit rough and needs some work but I was thinking to maybe wrap it behind a select option for the user? Within the bootstrap can check against user selection and include the css file the for the theme the user selected on his profile

Kind regards!

**Comment by RCyrix** [comment]
Its basically just 5 colors 

Background
Nav
Primary
Secondary
Accent 

Very straight forward.

Looking forward to hearing from you!

**Comment by open-admin-org** [comment]
@RCyrix that looks great! thanks for the support. I guess the best way would be create an extension. You find some information here: [https://open-admin.org/docs/en/extension-development](https://open-admin.org/docs/en/extension-development) 

It would be awesome to have night / day switch at the top menu :-D

In past i created this plugin [https://github.com/wishbone-productions/smooth-theme](https://github.com/wishbone-productions/smooth-theme) for laravel-admin. Maybe it helps with some inspiration and building an extension

**Comment by RCyrix** [comment]
Ok shall do and will revert! Thanks

**Comment by RCyrix** [comment]
Hi there! 

I hope all is well! Please excuse my patchy updates, been a bit of a rat race, 

Please see the following video and URL 

I decided to do a basic extension (Many more to come) but requesting that you please go over it and have a look at where I may have gone wrong or what can be improved, very simple module, adapted from Laravel-Admin Backup, just to get a basic feel of working with the extension paradigm

Please see attached video of functionality of Extension "open-admin-backup" 

and Github Repo https://github.com/RCyrix/open-admin-backup

[OA-Backup Demo.webm](https://github.com/open-admin-org/open-admin/assets/124294361/9a71b1cd-5da2-4c26-882a-6faebc9434a5)

Before tackling an Extension as big as the theme idea, I'd like to make sure I can do at least a small extension and get it right and if need be receive a bit of guidance. 

Kind regards

**Comment by RCyrix** [comment]
hi. any update on this?
