### ISSUE TITLE
Pop up modal - class Table not found

### ISSUE THREAD

**Issue by lordjack** [open-admin-org/open-admin#79]
**Describe the bug**
Hello guys, I'm trying to use the example pop up modal, as shown in this link here.

https://open-admin.org/docs/en/model-grid-actions#popup-form

However, it is presenting the following error:
Error
Class "app \ admin \ controllers \ table" not found.

I don't know which table I should import. Could anyone help?

Example: 
```php
$grid->column('title', 'title')->modal('latest comment', function ($model) {

    $comments = $model->comments()->take(10)->get()->map(function ($comment) {
        return $comment->only(['id', 'content', 'created_at']);
    });

    return new Table(['ID', 'content', 'release time'], $comments->toArray());
});
```

**System**
 - Open-admin version 1.0
 - PHP version 8.1
 - Laravel Version 8.75
 - OS: Windows
 - Browser Firefox

**Comment by mzangeneh** [comment]
Hi there
You should use 
`OpenAdmin\Admin\Widgets\Table`
class.

**Comment by lordjack** [comment]
> Hi there You should use `OpenAdmin\Admin\Widgets\Table` class.

Thanks for the tip, it worked!
