### ISSUE TITLE
File error form id with ->

### ISSUE THREAD

**Issue by loicgeek** [open-admin-org/open-admin#85]
**Describe the bug**
<img width="902" alt="image" src="https://github.com/open-admin-org/open-admin/assets/33604660/c9359242-1d88-4931-a03f-0e7955e477f8">
An error occured here when I tried to upload an audio file with id "audio->en"

**To Reproduce**
Steps to reproduce the behavior, for example:
 $form->file('audio->fr', __('Audio'))->attribute("accept","audio/*");

**Expected behavior**

**System**
 - Open-admin 1.0 
 - PHP 8.1
 - Laravel 10.10
 - OS: Mac
 - Browser Chrome

**Comment by RCyrix** [comment]
Hi there, you will need to change the name of that ID, its will not be valid, try something like audio_en

**Comment by RCyrix** [comment]
If you need that value in particular, try  setting an element data-attr and refer to it from that utilizing a seperate ID that wont cause failure on document selector

**Comment by loicgeek** [comment]
hello @RCyrix  thank for your quick reply, I am actually using the same for other field, like "title->en"

**Comment by RCyrix** [comment]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
You can then access the data attributes in the upload step via JS and pass the values to your script 

an alternative if you file open admin file upload does not suite your requirements is [bo](https://plugins.krajee.com/file-input)

but wil require jquery

**Comment by loicgeek** [comment]
The screenshot I posted above is from OA, it is where it setup script(with var) for upload process, but while declaring variables, it generate error because of the id I used

**Comment by RCyrix** [comment]
you cant use -> in an element id

**Comment by loicgeek** [comment]
exactly, the error occurs when it try to create a variable with my id

**Comment by RCyrix** [comment]
so its not a ID you have defined?

$form->file('audio->fr', __('Audio'))->attribute("accept","audio/*");

As you are setting the ID with the first parameter

**Comment by loicgeek** [comment]
```form->file('audio->fr', __('Audio'))->attribute("accept","audio/*");```
this is my code, I inspected OA code to see what is wrong, I found that it was  when It tried to declare the variable FileUpload_{$id}

**Comment by RCyrix** [comment]
you cannot use audio->fr as the ID  

The first parameter sets the ID

**Comment by loicgeek** [comment]
I think we should just found a better way to declare variables on Js part, like using an array

**Comment by RCyrix** [comment]
No i am sorry, I do not beleive this is a framework issue, set your IDs in a standard manner and it will work, you cannot set an element ID  to contain symbols....... try it, take a plain html page, add an element with an ID like that, and try to select that ID and get the element.

It will fail. This is not open  admin

**Comment by loicgeek** [comment]
@RCyrix  I just tried again, It worked

**Comment by RCyrix** [comment]
It seems im not able to help here,  I will leave it to the community to assist you

**Comment by loicgeek** [comment]
thanks for your time

**Comment by bytebrain** [comment]
@loicgeek Is your issue related to https://github.com/Astrotomic/laravel-translatable by any chance?

**Comment by loicgeek** [comment]
Hello @bytebrain it is not that exact plugin but I guess they use the same logic as spatie/translatable for translation

**Comment by bytebrain** [comment]
I had the same problem with an older project. Patched open-admin to get it to work. I will check this weekend and make a pull request for it.

**Comment by open-admin-org** [comment]
@bytebrain & @RCyrix  thank for pointing in the right direction. Will close this one. Made some additional change to the way javascript variable are used.

**Comment by loicgeek** [comment]
hello @bytebrain , can I have your change please
