### ISSUE TITLE
What is the prefered cmd to compile the scss?

### ISSUE THREAD

**Issue by bytebrain** [open-admin-org/open-admin#87]
I'm trying to make the `Application layout` settings in `config/admin` working for all documented values. I have some additions to `resources/assets/open-admin/scss/skeleton.scss` in the repo. What is the prefered cmd to compile the scss assets for testing and pull requests?

**Comment by RCyrix** [comment]
Perhaps this will be of use 

Open is based on bootstrap5, if you are interested in changing these styles you could take a look at
/vendor/open-admin-org/open-admin/resources/assets/open-admin/scss

These are compiled with sass via composer. You can run "composer sass" inside /vendor/open-admin-org/open-admin to create a new version of the css. Be aware you need to push you news styles to public root as well. Y
ou can use:
php artisan vendor:publish --provider="OpenAdmin\Admin\AdminServiceProvider"

To make development more easy i created myself a symbolic link between my asset folder in vendor dir and the vendor/open-admin dir in the public root.
