### ISSUE TITLE
hasMany relation field js not worked

### ISSUE THREAD

**Issue by Abdullajon8111** [open-admin-org/open-admin#91]
**Describe the bug**
hasMany relation field js not worked

2- 3- item

file upload not worked
inputmask not worked 
date_picker not worked

**Comment by Abdullajon8111** [comment]
choosen js not worked from hasMany relation fiield

**Comment by bytebrain** [comment]
Could you please specify errors, and give some code examples you have used?

**Comment by open-admin-org** [comment]
now fixed in will release soon.
